export { default as Main } from './Main.js'
export { default as Home } from './Home'
export { default as Navbar } from './Navbar'
export { default as Campuses } from './Campuses'
export { default as SingleCampus } from './SingleCampus'
export { default as Students } from './Students'
export { default as SingleStudent } from './SingleStudent'
export { default as StudentList } from './StudentList'